# Generated by Django 4.0.3 on 2022-04-30 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=50)),
                ('customer_full_name', models.CharField(max_length=200)),
                ('customer_phone_number', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=40)),
                ('issue_description', models.TextField(max_length=1000)),
                ('urgent_status', models.BooleanField(default=False)),
                ('completed_status', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
