# Generated by Django 4.0.4 on 2022-05-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_alter_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_section',
            field=models.CharField(blank=True, choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Applications', 'Applications'), ('Infrastructure and Networking', 'Infrastructure and Networking'), ('Database Administrator', 'Database Administrator')], max_length=30, null=True),
        ),
    ]
